### ISSUE TITLE
[리서치] 쿠버네티스로 로컬 개발환경 셋팅

### ISSUE THREAD

**Issue by seokhwan-an** [choorai/excuse-me-backend#34]
## 개요
쿠버네티스를 클라우드 서버에 올리기 앞서서 로컬 환경으로 테스트 하기 위한 개발환경 셋팅

## 기대효과
- 팀원들이 로컬환경에서 쿠버네티스에 대한 다양한 실험 가능
- 쿠버네티스에 대한 숙련도 향상

## 진행
- [x] 쿠버네티스에 대한 기본 개념 학습
- [x] 쿠버네티스 로컬 환경 세팅
- [x] 테스트 용 배포해보기
- [x] 문서화

**Comment by seokhwan-an** [comment]
## 1일차

### kubernete와 관련된 용어 정리
- 워크로드(workload): Kubernetes에서 구동되는 애플리케이션을 의미하며 한 개 혹은 여러 개의 pod들로 구성됨
- 파드(pod): 쿠버네티스에서 생성하고 관리할 수 있는 배포 가능한 가장 작은 단위로 하나 이상의 컨테이너 그룹
     - 같은 pod 안에 있는 컨테이너들은 리소스를 공유함

![kuberentes](https://github.com/choorai/excuse-me-backend/assets/70303795/d584a54c-6d86-4913-b575-04d070cd8c73)
워크로드와 파드를 배달의 민족 서비스에 빗대서 살펴보면 워크로드는 배달의 민족 서비스를 의미하며 파드는 배달의 민족 서비스를 구성하는 각각의 시스템으로 결제 시스템, 주문 시스템, 배달 시스템으로 볼 수 있다.

### Kubernetes를 이용하는 이유
- 컨테이너들을 관리하고 조율 하기 위해서 Kubernetes를 이용함
    - 하나의 컨테이너가 트래픽 부하나 에러로 인해 다운이되었을 때 이를 개발자가 확인하고 재실행을 하게 되면 서비스가 중단되어 있는 시간이 길어짐
    - 즉, 컨테이너를 실시간으로 관리할 수 서비스가 필요함

### Kubernetes가 제공하는 기능
- 서비스 디스커버리와 로드 밸런싱
- 스토리지 오케스트레이션
- 자동화된 롤아웃과 롤백
- 자동화된 빈 패킹
- 자동화된 복구
- 시크릿과 구성 관리

### 참고자료
- [Kubernetes 공식문서](https://kubernetes.io/ko/docs/concepts/overview/)

### 내일 할 일
- 쿠버네티스 로컬 환경 세팅하기

**Comment by seokhwan-an** [comment]
## 2일차
### 사전 도구 설치
- MiniKube: 로컬 환경에서 Kubernetes를 쉽게 실행할 수 있는 도구
- Kubectl: Kubectl은 Kubernetes의 Cluster와 통신하여 다양한 Object를 관리할 수 있는 CLI 도구
```
// MiniKube 설치
brew install minikube

// kubectl 설치
brew install 
```
### Minikube 사용하기
- minikube 를 실행하는 명령어
```
// Kubernetes의 버전을 명시해 실행하는 명령어
minikube start --kubernetes-version [실행할려는 버전]

// 가장 최신버전으로 실행하는 명령어
minikube start

// 다중 노드로 실행하는 명령어
minikube start -n 2
```

![k1](https://github.com/choorai/excuse-me-backend/assets/70303795/f9ab8d01-c66a-4769-9880-00fd120b3349)
![k2](https://github.com/choorai/excuse-me-backend/assets/70303795/e1d8b075-442f-46b8-b5bb-88c77cb59f02)
![k3](https://github.com/choorai/excuse-me-backend/assets/70303795/de2f12d5-8cd8-43c5-a5ea-a5329ab34720)

위와 같이 실행 명령어를 입력하면 docker image를 다운로드 받고 이를 통해서 minikube container를 실행해 Kubernetes cluster를 생성합니다.

- minikube를 사용하는 다른 명령어
```
// minikube를 일시정지하는 명령어
minikube pause

// minikube를 재가동하는 명령어
minikube unpause

// minikube를 종료하는 명령어
minikube stop

// minikube를 삭제하는 명렁어
minikube delete --all
```

### 참고자료
- https://www.devkuma.com/docs/kubernetes/minikube/

### 내일 할일
- minikube를 통해서 pod 생성 및 테스트 배포해보기

**Comment by seokhwan-an** [comment]
## 3일차
### 사전 준비사항
- docker compose를 실행해 놓는다. 
## 배포

### minikube 실행

```java
minikube start
```

- docker compose가 실행되어 있지 않은 경우에 minikube를 실행한 경우
    
![deploy1](https://github.com/choorai/excuse-me-backend/assets/70303795/a1f7e77b-56ea-43b6-a1bc-5758193fb8ba)


### Deploy yaml 작성

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

```

1. apiVersion : 오브젝트를 생성하기 위해 사용한 쿠버네티스 API 버전 명세 
    - apps/v1 :쿠버네티스의 common API 모음
    - autoscaling/v1 : pod의 autoscale 기능을 포함하는 api
2. kind: 생성할 쿠버네티스의 object 타입
    - Deployment : 코드 배포를 제어할 수 있는 object로 pod 복제, 배포 일시중지, 재개 및 롤백이 가능
    - Service: 쿠버네티스에서 다양한 어플리케이션을 올리고 어플리케이션 간 통신에 활용
    - Ingress: 클러스터 내의 서비스에 대한 외부접근을 관리하는 오브젝트
    - job: 배치 오브젝트, 주기적으로 스케쥴링된 테스크를 수행할 때 사용
3. metadata: Deployment 오브젝트의 이름을 정의하는 것입니다.

### deploy yaml 실행

```yaml
kubectl apply -f ./nginx-deployment.yaml

// 실행결과 성공시 (아래와 같은 문구가 나타남)
deployment.apps/nginx-deployment created
```

```yaml
// 생성된 pod 확인해보기
kubectl get pod
```

![deploy2](https://github.com/choorai/excuse-me-backend/assets/70303795/29fcda59-7555-4fe9-8608-52b69662523f)


- replica 까지 2개의 pod가 생성

### dashboard 이용하기

```yaml
minikube dashboard // 💡다음 명령어는 minikube가 실행된 터미널이 아닌 새 터미널을 띄우고 작성해야한다.
```
![deploy3](https://github.com/choorai/excuse-me-backend/assets/70303795/2a1194e3-3ad5-4af6-b4b3-7f407a1fbd78)


### Service yaml 작성

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx // nginx-deployment에서 지정한 selector 이름과 같아야 한다. 
  ports:
    – targetPort: 80
      port: 80
      nodePort: 30080
      
```

- 생성된 pod를 외부에서 접근할 수 있게 설정하는 yaml

### Service yaml 실행

```yaml
kubect; apply -f ./nginx-service.yaml

// 실행결과 성공시 (아래와 같은 문구가 나타남)
service/nginx-service created
```

### 배포한 nginx에 접속하기

```yaml
minikube service nginx-service --url 

// 실행결과 (다음과 같이 주소를 안내 해준다)
http://127.0.0.1:50309
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.
```

- 설정한 service를 실행

생성된 주소에 접근하면 nginx가 배포된 것을 확인할 수 있습니다.

![deploy4](https://github.com/choorai/excuse-me-backend/assets/70303795/d7face16-ba78-4cbd-9346-47977b6a9a2f)


## 참고자료

- [[https://idchowto.com/minikube-로-nginx-배포/](https://idchowto.com/minikube-%EB%A1%9C-nginx-%EB%B0%B0%ED%8F%AC/)](https://idchowto.com/minikube-%EB%A1%9C-nginx-%EB%B0%B0%ED%8F%AC/)
- https://github.com/kubernetes/minikube/issues/17208
- https://kubernetes.io/docs/concepts/overview/working-with-objects/
